#!/usr/bin/env bash
# Install systemd units so Compose starts on boot (golden / appliance path).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
resolve_host_root() {
  if [[ -f "${SCRIPT_DIR}/../conf/systemd/doombox-compose.service" ]]; then
    cd "${SCRIPT_DIR}/.." && pwd
    return 0
  fi
  if [[ -f /etc/default/doombox ]]; then
    # shellcheck source=/dev/null
    source /etc/default/doombox
    if [[ -n "${DOOMBOX_BOX_ROOT:-}" && -f "${DOOMBOX_BOX_ROOT}/host/conf/systemd/doombox-compose.service" ]]; then
      printf '%s\n' "${DOOMBOX_BOX_ROOT}/host"
      return 0
    fi
  fi
  if [[ -f /opt/doombox/host/conf/systemd/doombox-compose.service ]]; then
    printf '%s\n' /opt/doombox/host
    return 0
  fi
  return 1
}

HOST_ROOT="$(resolve_host_root)" || {
  echo "ERROR: cannot locate box/host tree (run from repo or set DOOMBOX_BOX_ROOT)" >&2
  exit 1
}
BOX_ROOT="$(cd "${HOST_ROOT}/.." && pwd)"
# shellcheck source=lib/host-env.sh
source "${HOST_ROOT}/scripts/lib/host-env.sh"

log() { printf '==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

PULL_REMOTE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pull-remote-desktop) PULL_REMOTE=1; shift ;;
    -h|--help)
      cat <<'EOF'
Usage: sudo ./scripts/install-compose-boot.sh [--pull-remote-desktop]

Installs /etc/default/doombox, compose up/down helpers, first-boot + compose
systemd units, and enables them. Does not build images (enable-compose-stack does).
EOF
      exit 0
      ;;
    *) die "unknown arg: $1" ;;
  esac
done

[[ "${EUID}" -eq 0 ]] || die "run as root"
command -v docker >/dev/null || die "docker required"

DOOMBOX_BOX_ROOT="${DOOMBOX_BOX_ROOT:-${BOX_ROOT}}"
[[ -f "${DOOMBOX_BOX_ROOT}/compose/docker-compose.yml" ]] \
  || die "compose missing under ${DOOMBOX_BOX_ROOT} (set DOOMBOX_BOX_ROOT)"

install -d -m 0755 /etc/default
install -d -m 0755 /var/lib/doombox
install -d -m 0755 /usr/local/sbin
install -d -m 0755 /usr/local/lib/doombox
install -d -m 0755 /etc/systemd/system

# Prefer installed tree path; fall back to this checkout for lab boxes.
cat >/etc/default/doombox <<EOF
# Generated by install-compose-boot.sh — appliance Compose root (the box/ tree)
DOOMBOX_BOX_ROOT=${DOOMBOX_BOX_ROOT}
DOOMBOX_STORAGE=${DOOMBOX_STORAGE:-/mnt/storage}
EOF
chmod 0644 /etc/default/doombox
log "Wrote /etc/default/doombox (DOOMBOX_BOX_ROOT=${DOOMBOX_BOX_ROOT})"

install -m 0644 "${HOST_ROOT}/scripts/lib/host-env.sh" /usr/local/lib/doombox/host-env.sh
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/compose-up.sh" /usr/local/sbin/doombox-compose-up
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/compose-down.sh" /usr/local/sbin/doombox-compose-down
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/first-boot.sh" /usr/local/sbin/doombox-first-boot
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/prepare-golden.sh" /usr/local/sbin/doombox-prepare-golden
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/bake-golden.sh" /usr/local/sbin/doombox-bake-golden
install -m 0750 -o root -g root "${HOST_ROOT}/scripts/install-compose-boot.sh" /usr/local/sbin/doombox-install-compose-boot

install -m 0644 \
  "${HOST_ROOT}/conf/systemd/doombox-first-boot.service" \
  /etc/systemd/system/doombox-first-boot.service
install -m 0644 \
  "${HOST_ROOT}/conf/systemd/doombox-compose.service" \
  /etc/systemd/system/doombox-compose.service

if [[ "${PULL_REMOTE}" -eq 1 ]]; then
  log "Pre-pulling remote-desktop profile images (desktop stays off until Settings enable)"
  (
    cd "${DOOMBOX_BOX_ROOT}"
    [[ -f .env ]] || cp .env.example .env
    docker compose -f compose/docker-compose.yml --env-file .env --profile remote-desktop pull
  )
fi

if doombox_has_systemd; then
  systemctl daemon-reload
  systemctl enable doombox-first-boot.service
  systemctl enable doombox-compose.service
  # Run first-boot once now (no-op for claim on non-clone); then ensure stack is up.
  systemctl start doombox-first-boot.service || true
  systemctl start doombox-compose.service
  log "Enabled + started doombox-compose.service"
else
  log "No systemd — helpers installed; start manually: doombox-compose-up"
fi

log "Boot path ready. Clones: doombox-prepare-golden → image → flash → power on."
