upstream doombox_api {
    server api:8090;
}

upstream doombox_dashboard {
    server dashboard:80;
}

server {
    listen 80 default_server;
    server_name box.local doomsday.local box.heyeddi.local doomsday.heyeddi.local _;

    client_max_body_size 32m;

    location /api/ {
        proxy_pass http://doombox_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Doombox-Host $host;
    }

    location / {
        proxy_pass http://doombox_dashboard;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Doombox-Host $host;
    }
}
